language: node_js
node_js:
  - '12'
  - '10'
  - '8'
env:
  - TEST_SUITE=test
  - TEST_SUITE=bench
script: npm run-script $TEST_SUITE
after_success: npm run coverage
notifications:
  email:
    on_success: never
